### ISSUE TITLE
Watch mode?

### ISSUE THREAD

**Issue by unsafecode** [tettusud/merge-jsons-webpack-plugin#11]
Does this work in watch mode / dev-server? Having this config:

```javascript
new MergeJsonWebpackPlugin({
            "output": {
                "groupBy": ["it", "en", "fr"].map(lang => ({
                    "pattern": `**/*.${lang}.json`,
                    "fileName": `${METADATA.isDevServer ? "src" : "wwwroot"}/assets/i18n/${lang}.json`
                }))
            }
        }),
```

Output files don't look like to be updated when any of the source files change. I need to restart webpack in order to have them updated.

I also tried with `--watch-content-base`, but it seems ineffective.

**Comment by twkx** [comment]
I have the exact same problem.

Is it a plugin issue, or a mistake in our config file ?

**Comment by tettusud** [comment]
I found the issue I will release a new version

**Comment by tettusud** [comment]
Hi @unsafecode  and @twkx 
  This issue has been resolved, please get the latest version 1.0.6 and give a try.
I thank you very much for taking interest in the plugin and highlighting the issues.
Please let me know if the issue still persists.

**Comment by twkx** [comment]
Thanks a lot @tettusud, your fix works very well and my labels are now correctly merged in watch mode :)

Best regards,

**Comment by unsafecode** [comment]
@tettusud Thanks!
