### ISSUE TITLE
Error management

### ISSUE THREAD

**Issue by unsafecode** [tettusud/merge-jsons-webpack-plugin#12]
It looks like error handling should be done differently, as explain in this SO question:

http://stackoverflow.com/questions/42364742/webpack-plugin-error-management

Otherwise, error will not reported in the output.

Found this issue while debugging why merge stopped writing files without any visibile error.

**Comment by tettusud** [comment]
Thank you @unsafecode will try to implement it 
Thank you very much for pointing it out.

Sent from my HTC

----- Reply message -----
