### ISSUE TITLE
Issues when merging with wrong encoding

### ISSUE THREAD

**Issue by wsloth** [tettusud/merge-jsons-webpack-plugin#14]
It seems that UTF-8 encoding works properly, but with other encodings I'll get errors that invalid characters have been encountered in line 0 position 0, even though that is a `{` for me.

**Comment by tettusud** [comment]
hi @wsloth 
  I have published a new version 1.0.7 ,please use that.  pass encoding in the options as explained .
 `  new MergeJsonWebpackPlugin({
           "encoding":"ascii",
            "output": {
                "groupBy": [{
                    "pattern": "{./node_modules/module*/en.json,./jsons/file1.json}",
                    "fileName": "./out/module1/module2/en.json"
                },
               {"pattern": "./jsons/module*/es.json", "fileName": "./dist/es.json"}]
            }`

**Comment by wsloth** [comment]
Wow, thanks for the incredible speed of the fix! Works great 👍
