### ISSUE TITLE
Use webpack's in-memory filesystem with webpack-dev-server

### ISSUE THREAD

**Issue by Loetn** [tettusud/merge-jsons-webpack-plugin#15]
Hello

At the moment, this webpack plugin copies the merged files to a directory via 'fs', even when we're using webpack-dev-server. Is it possible to use webpack's [in-memory filesystem](https://webpack.github.io/docs/webpack-dev-server.html#content-base) with webpack-dev-server, just like [copy-webpack-plugin](https://github.com/kevlened/copy-webpack-plugin)? This way, there is lesser possibility to have path issues. 

Thanks!

**Comment by tettusud** [comment]
@Loetn Good suggestion,I will try to implement the same and will let you know.

**Comment by Loetn** [comment]
@tettusud [This commit](https://github.com/kevlened/copy-webpack-plugin/commit/46ab44d983cf580782efe7f2f067babdb5095565) is the one that added this functionality in copy-webpack-plugin.

**Comment by tettusud** [comment]
@Loetn  I started working on this, I will let you know once done.Thank you

**Comment by tettusud** [comment]
@Loetn 
   I have published a new version 1.0.8 , please get the latest and check , now you can mention relative path as output file name,I hope this should solve your path issues.
  If you still face any issues let me know.Thank you

**Comment by Loetn** [comment]
@tettusud This solves my webpack/path issues. Thanks for the fast update!
