### ISSUE TITLE
postinstall script 'typings install' fails

### ISSUE THREAD

**Issue by dominiksteiner** [tettusud/merge-jsons-webpack-plugin#2]
npm i merge-jsons-webpack-plugin --save

merge-jsons-webpack-plugin@1.0.2 postinstall /Users/dominiksteiner/Documents/workspace-broadsoft/hub/hubLib/node_modules/merge-jsons-webpack-plugin
typings install

sh: typings: command not found
....
npm ERR! merge-jsons-webpack-plugin@1.0.2 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the merge-jsons-webpack-plugin@1.0.2 postinstall script 'typings install'.

Is there some dependency on globally installed typings?

**Comment by tettusud** [comment]
Thank you @dominiksteiner for trying the plugin, I have fixed the issue in release **1.0.3**
You can take latest.
Basically its trying to install typings after  installing packages, and expecting typings to be present .
I modified reference to postinstall

Regards
Sudharsan tettu

**Comment by dominiksteiner** [comment]
thanks @tettusud installation works well now
