### ISSUE TITLE
UTF8 with BOM not workin

### ISSUE THREAD

**Issue by jogibear9988** [tettusud/merge-jsons-webpack-plugin#22]
The plugin does not work when you use  Utf8 files with a Bom!

**Comment by tettusud** [comment]
@jogibear9988  could you please provide your sample Jsons?

**Comment by tettusud** [comment]
@jogibear9988  please check the accepted answer here https://stackoverflow.com/questions/2223882/whats-different-between-utf-8-and-utf-8-without-bom

**Comment by jogibear9988** [comment]
It would be a one liner to detect the bom and remove it.

https://www.npmjs.com/package/strip-bom

**Comment by tettusud** [comment]
new version 1.0.18 released to fix this issue

**Comment by pardoman** [comment]
That's great, thanks!
