### ISSUE TITLE
output file not being generated

### ISSUE THREAD

**Issue by asaldivar** [tettusud/merge-jsons-webpack-plugin#23]
Thanks for such an amazing plugin!

For some reason an output file is not being generated for me in my own app as well as the example app you have. 

My app:

```
  plugins: [
    new MergeJsonWebpackPlugin({
      "files": [
        'trimmers/entry1506670635260.json',
        'trimmers/entry1507044430282.json'],
      "output": {
        "fileName":"test.json"
      }
    })
  ]
```

Webpack runs without any issues, but no `test.json` file is created for me. I was expecting to see `test.json` generated in my root, but I'm not seeing anywhere in the application. Am I missing a step?

Thank you

**Comment by asaldivar** [comment]
I also tried the following with no success:

```
    new MergeJsonWebpackPlugin({
      "output": {
        "groupBy": [
          {
            "pattern": "trimmers/*.json",
            "filename": "test.json"
          }
        ]
      }
    })
```

**Comment by tettusud** [comment]
Thank you @asaldivar  for the feedback, may I know what is your configuration for output?
file will be created relative to this path for eg below file will be created inside your app build/test.json
```
output: {
    path: path.resolve(__dirname, "build"),
    ....
   }
```

**Comment by asaldivar** [comment]
Thanks for the response!

My output path is 

output: path.resolve(__dirname, '../dist')

But I don't see the generated test.json file in my dist folder.

**Comment by asaldivar** [comment]
Here is the full output object:

```
output: { path: '/Users/asaldivar/freelance/trimmer-work/dist',
  filename: '[name].js',
  publicPath: '/' }
```

**Comment by asaldivar** [comment]
If it helps at all, I'm using the vuejs webpack template: https://github.com/vuejs-templates/webpack

**Comment by asaldivar** [comment]
I've been using the `vue-gh-pages` and it has been sending my generated `.json` file to a `/docs` directory. Mystery solved. Still not sure why it wasn't working for me in your example but I'm at a point where I can figure out the rest in my own application. Thank you!
