### ISSUE TITLE
Getting file not found for Dynamic Generated files

### ISSUE THREAD

**Issue by nishantkagrawal** [tettusud/merge-jsons-webpack-plugin#25]
I am using webpack-angular-translate plugin to dynamically generate a json file (say A.json) and then merge it with an  existing json (say B.json). 

I get ERROR in MergeJsonWebpackPlugin: MergeJsonWebpackPlugin: Unable to locate file A.json

Is it possible to merge the files from compilation.assets?

I tried with the following change to readFile and it worked for me
https://github.com/nishantkagrawal/merge-jsons-webpack-plugin/commit/e4afddcb263a82bb0915911a22218d8f81b5c86e

**Comment by tettusud** [comment]
@nishantkagrawal HI I will test once and release a new version.Thank you for helping with the code.

**Comment by tettusud** [comment]
@nishantkagrawal  i have published new version 1.0.13 ,could you please check that? You do not need to mention anything separately to use files from assets. By default it will check for files if not found on the path.It will look for assets ,and load it .Could you review the code if its fine?

**Comment by nishantkagrawal** [comment]
Works as expected! Code looks good as well! Thanks!
