### ISSUE TITLE
`plugin.fileDependencies` grows with each compilation.

### ISSUE THREAD

**Issue by santiago-elustondo** [tettusud/merge-jsons-webpack-plugin#28]
It looks like when you concatenate dependencies onto the `plugin.fileDependencies` array, it is adding these to the saved dependencies from the previous run.
```
this.fileDependencies = this.fileDependencies.concat(files);
```
here's some console output:
![image](https://user-images.githubusercontent.com/10526720/35738143-f9f60fa4-07fb-11e8-837c-3df5f9940481.png)

**Comment by tettusud** [comment]
Yeah I noticed it I will give a fix clubbing with others

**Comment by tettusud** [comment]
@santiago-elustondo thank you very much. Its resolved in new version
