### ISSUE TITLE
How do I prevent structural changes to the json?

### ISSUE THREAD

**Issue by jbeckton** [tettusud/merge-jsons-webpack-plugin#3]
In my source json files I have an array of objects.

    `"children": [
        {
          "role": "link",
          "title": "Sub One",
          "routerLink": "/spog-module-seed/sub-one"
        },
        {
          "role": "link",
          "title": "Sub Two",
          "routerLink": "/spog-module-seed/sub-two"
        }
    ]`

and the result becomes 

    `"children": {
          "0": {
            "role": "link",
            "title": "Sub One",
            "routerLink": "/spog-module-seed/sub-one"
          },
          "1": {
            "role": "link",
            "title": "Sub Two",
            "routerLink": "/spog-module-seed/sub-two"
          }
    }`

is there a way to influence this behavior so the output contains and array of objects?

**Comment by tettusud** [comment]
Thank you @jbeckton  for trying the plugin , I have fixed the issue you can download the latest version 1.0.4
By the way you can also try running the sample  ,I have added new folders under example/jsons/arrays ,which explains your scenerio
