### ISSUE TITLE
Keep file names as parent object of content in merged files

### ISSUE THREAD

**Issue by Mindtraveller** [tettusud/merge-jsons-webpack-plugin#31]
Hi, 
Do you plan to add the possibility to keep file names in result file?

The example:
There are separate i18n files:
```
sign_in.json

{  
    "submit": "Sign in"
}
```
```
sign_up.json

{
    "submit": "Sign up" 
}
```
I'd like to have following structure of the resulting file:
```
{ 
    "sign_in": { 
        "submit": "Sign in"
    }, 
    "sign_up": { 
        "submit": "Sign up"
    }
}
```

**Comment by tettusud** [comment]
Sure let me try to add it up.

**Comment by Mindtraveller** [comment]
Thank you!

**Comment by tettusud** [comment]
I have given a new release 1.0.15 ,please check, you need to pass option prefixFileName as true, in order to prefix the file names.
