### ISSUE TITLE
Can't manage to get the result file generated and saved

### ISSUE THREAD

**Issue by rmartin94** [tettusud/merge-jsons-webpack-plugin#34]
Hi, I'm having some trouble to get the proper merged json file created and saved within my project. The base structure is as follows:

```
-TestApp
  -e2e
  -node_modules
  -src
      -app
      -assets
      -enviornments
  -dist
       [empty]
  -jsons
      *test1.json
      *test2.json
      *test3.json
   ...
  *webpack.config.json
```

While the plugin config is defined like:

```
"plugins": [
    new MergeJsonWebpackPlugin({
      "debug": true,
      "files": [
        "./jsons/test1.json",
        "./jsons/test2.json",
        "./jsons/test3.json"
      ],
      "output": {
        "fileName": "./dist/result.json"
      }
    }),
```
If I npm start the project (which will run webpack-dev-server --port=4200) then I console log the response from the processFiles method in the plugin then I actually get the content of the meant file to be written, but its never saved.

```
Response {
  filepath: './dist/result.json',
  content: '{"HELLO":"hello world","SOMETHING":"this is something","TESTING":"this is just a test"}' 
}
```
Also, the console output shows something regarding the file

```
            Asset            Size        Chunks             Chunk Names
     ...
     ./dist/result.json   87 bytes               [emitted]
     ...
```

I've also tryed some other configurations with no success such as;

```
"plugins": [
    new MergeJsonWebpackPlugin({
      "debug": true,
      "output": {
        "groupBy": [
          {
            "pattern": "./jsons/*.json",
            "fileName": "./dist/result.json"
          }
        ]
      }
    }),
```

Is this an issue from the plugin? I'm doing something wrong on config? Thanks.

**Comment by tettusud** [comment]
Remove ./ from the filenames and give a try , 
 "files": [
        "jsons/test1.json",
        "jsons/test2.json",
        "jsons/test3.json"
      ]
`

check the example folder for sample usage

**Comment by rmartin94** [comment]
Hi! Thanks for the reply. Yes, I've also tryed this. Never the less the file is not generated, the dist folder is still empty. By running npm start, this command is executed - which I suppose is the right one for running webpack plugins

```
"scripts": {
    "start": "webpack-dev-server --port=4200"
  }
```

**Comment by tettusud** [comment]
Yeah , you need to run build command to actually generate the file
