### ISSUE TITLE
Extension restriction

### ISSUE THREAD

**Issue by expressiveco** [tettusud/merge-jsons-webpack-plugin#37]
File extension should not be restricted to "json".

I am frustrated of it and come up with a simple way to merge jsons;

https://gist.github.com/expressiveco/56cb9d0531821d237d78b99efa40a1cb

**Comment by tettusud** [comment]
Instead you just fork this repo, remove that check and use it. Anyway thanks for your suggestions.

**Comment by tettusud** [comment]
File extension check removed as suggested. Thank you for the suggestion.The code is available on the master and new version 1.0.17
