### ISSUE TITLE
Pattern does not find files

### ISSUE THREAD

**Issue by LeonsBuntis** [tettusud/merge-jsons-webpack-plugin#44]
Deriving from 2nd example "2) By Patterns" I've created my config:
`new MergeJsonWebpackPlugin({
        "encoding": "ascii",
        "debug": true,
        "output": {
            "groupBy": [
                {
                    "pattern": "{./**/translations/*.en.json}",
                    "fileName": "./assets/locale/en.json"
                },
                {
                    "pattern": "{./**/translations/*.fr.json}",
                    "fileName": "./assets/locale/fr.json"
                }
            ]
        },
        "globOptions": {
            "nosort": true
        }
    })`

The output files are both empty using these patterns. But when I added `,` resulting in 
`"pattern": "{./**/translations/*.en.json,}"`,
`"pattern": "{./**/translations/*.fr.json,}"`. 
It started to work, seems like some object parsing bug :)

**Comment by tettusud** [comment]
hi @LeonsBuntis ,  yeah you may need to exclude {} if there is only one pattern. As its already mentioned in the readme document under section 2.

groupBy | Array of patterns and corresponding fileNames. |  
-- | -- | --
groupBy[].pattern | Pattern to search files for. eg: **/en.json will pull all en.json files under current working directory and sub directories |  
  | Do not use curly brackets if there is only single pattern to consider | pattern:"./node_modules/**/en.json"
  | Use curly brackets to group more than one pattern together | pattern:"{./node_modules/**/en.json,./src/assets/i18n/en.json}"
