### ISSUE TITLE
Merged json files seem to be minified per default

### ISSUE THREAD

**Issue by ampersand83** [tettusud/merge-jsons-webpack-plugin#50]
When merging two json files a and b the resulting merged json file c seems to be minified although I am in a development environment. Is there an option I can set to configure whether the resulting json file should be minified or not? 
If not this would be a really nice feature to implement in a future version.

**Comment by tettusud** [comment]
Noted, thanks for using the plugin, let me check and revert

**Comment by tettusud** [comment]
I have published new release 0.0.20. You need to pass `space:{number}` option to pretty print.For further details check readme / examples
