### ISSUE TITLE
Add ability group by the same name

### ISSUE THREAD

**Issue by DrNecromant** [tettusud/merge-jsons-webpack-plugin#55]
Assume, I have locales from different libraries
lib1/locales/*.json
lib2/locales/*.json

And I want to merge them the same way as merge-webpack-plugin does with option
group: '[name]',

With this option I do not need to specify each file name in configuration and fully rely on similarity of names in different folders (for example, 'lib1/locales/en_US.json', 'lib2/locales/en_US.json')

Unfortunately merge-webpack-plugin is outdated and does not work with webpack 4

**Comment by tettusud** [comment]
Hi thanks for trying it out but could you be specific what didn’t work with Webpack4.
 I tested it using Webpack 4, I was able to. But if you have any specific error could you share so I can take a look
