### ISSUE TITLE
Previous content overwritten instead of added to

### ISSUE THREAD

**Issue by ssuess** [tettusud/merge-jsons-webpack-plugin#56]
I have a pattern of language specific folders (`/src/i18n/en`,`/src/i18n/es`, etc) that I am matching to find files under each and merge them, but using the following code, the output file only contains the last language. I realize this is probably because inside each language file the structures are the same, ie:

`{ "helloMsg": "hello" }` and `{ "helloMsg": "hola" }` 

instead of

`{ "en": { "helloMsg": "hello"} }`  and `{ "es": { "helloMsg": "hola"} }` 

Is there a way for this plugin to write the pattern name of the folder into each grouping before writing it to the file? My translation software unfortunately seems to need me to keep the pattern above for it to be able to write those files to the folders properly.

Below is what my current code looks like
```
new MergeJsonWebpackPlugin({
            "debug": true,
            "output": {
              "groupBy": [
                  {
                      "pattern": "./src/i18n/*/item-specific/ThisItem.json",
                      "fileName": "./src/i18n/compiled/ThisItem.json"
                  },
                  {
                      "pattern": "./src/i18n/*/item-specific/ThatItem.json",
                      "fileName": "./src/i18n/compiled/ThatItem.json"
                  },
              ]
            },
            "globOptions": {
                "nosort": true
            }
          })
```

**Comment by tettusud** [comment]
There is an option prefix file name did you try that ?

**Comment by ssuess** [comment]
This isn't a file naming problem. It is a file content problem. But in any event, I just wrote my own script to take care of the merging I need. Thanks anyway.
