### ISSUE TITLE
Override globOptions with defaults only if none are provided

### ISSUE THREAD

**Issue by doshprompt** [tettusud/merge-jsons-webpack-plugin#57]
https://github.com/tettusud/merge-jsons-webpack-plugin/blob/master/index.js#L217

The order should be reversed so if cwd and mark are explicitly provided they are not replaced by the defaults.

Right now, no matter what mark and/or cwd are provided they will always revert to the default globOptions

**Comment by tettusud** [comment]
Thanks @doshprompt  released a new version 1.0.21
