### ISSUE TITLE
Dev mode support

### ISSUE THREAD

**Issue by scriby** [tettusud/merge-jsons-webpack-plugin#6]
It seems that in dev mode that the merged json file doesn't get updated after making changes to the input json files. I can see the merge plugin re-running, but it's as if it's operating on a cache of the files or something b/c the output file does not include the updated data.

Is this what you would expect?

Here's my config:

```
new MergeJsonWebpackPlugin({
      output: {
        groupBy: [
          {
            pattern: "**/*.loc.json",
            fileName:"./localization/en/translations.json"
          }
        ]
      }
    })
```

**Comment by tettusud** [comment]
How are you making use of generated json file? can you explain little bit more with your code.
From your explanation,looks like the plugin is loaded and new file is getting generated.
  But the code where you are referring to the generated file may not be reloading the new file.You may need to look into that perspective.

**Comment by tettusud** [comment]
If its working I would like to close this,you may reopen if you face any issues.

**Comment by tettusud** [comment]
@datnordstrom  ,you dont need to do anything separate. Just copy  example folder in this repository.If you are using webpack-dev-server start it in --inline mode. And any chnages you do to your json will be picked up and will generate output.
