### ISSUE TITLE
Webpack doesn't watch my json files for changes

### ISSUE THREAD

**Issue by Kequc** [tettusud/merge-jsons-webpack-plugin#8]
Experimenting using this plugin, I have to restart webpack before it cares about changes to the json files referenced. I'm not a webpack expert. Is there a way the centralised json files can be updated automatically when file changes are detected?

Thank you for your help.

**Comment by tettusud** [comment]
Hi @Kequc , if you are using webpac-dev-server could you try with --watch-content-base flag?

**Comment by tettusud** [comment]
If you still face any issue,please let me know,for now closing the issue.
